#配置内置Tomcat端口
server:
  port: 10000
spring:
  application:
    name: jw-workflow-engine-test
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  #配置数据源
  datasource:
    url: jdbc:mysql://47.100.202.245:3306/workflow?useUnicode=true&characterEncoding=utf8
    driverClassName: com.mysql.jdbc.Driver
    username: jiawei
    password: Fjw@4015.

  jackson:
    #字段为null时不返回该字段
    default-property-inclusion: non_null
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

#日志配置
logging:
  level:
    root: info

#mybatis配置
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.nengchen
  configuration:
    #开启驼峰匹配
    map-underscore-to-camel-case: true
    #开启sql语句打印
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #redis配置



